### ISSUE TITLE
Did this work also on mobile ?

### ISSUE THREAD

**Issue by f3ltron** [FlutterWithGia/FD-Project-Management#12]
I just see your video on youtube and It's crazy. But I did'nt see you running it on ios nor android. Is it actually working on them ?

**Comment by dinoudon** [comment]
I tried it in android and it is working but you need to readjust widgets positioning since it give landscape view when your device position in portrait. There are also overflow in some widgets.

(using bluestack5, 1080*1920, 240dpi)
![Screenshot_2021 11 02_11 53 18 509](https://user-images.githubusercontent.com/8967055/139788836-4d52796b-1bd6-4db7-acb5-91be146ab307.png)

![Screenshot_2021 11 02_11 53 25 925](https://user-images.githubusercontent.com/8967055/139788830-95e19904-c8f0-43ac-9ddf-3d87efa9b3b0.png)

**Comment by FlutterWithGia** [comment]
now this dashboard ready for tablet & mobile.
